import Foundation
import Testing

@testable import ArtscribeUI

/// Recents surviving an app update on iOS.
///
/// Reported twice from a device, and the second report is what proves the first
/// fix was incomplete: the sample was moved out of the read-only *bundle*
/// container, which fixed that UUID and inherited the **data** container's. Both
/// are regenerated by the system, both are embedded in the absolute path the
/// recents list persists, and iOS migrates the preferences across intact — so
/// the list comes back looking healthy and every entry in it is dead.
///
/// Measured on a simulator: a reinstall moved the data container from
/// `F465616D-…` to `312E214E-…` while `recentFiles` still held the first.
@Suite("Recent paths across an app update")
struct RecentPathAnchorTests {

    private static let oldHome =
        "/Users/x/Library/Developer/CoreSimulator/Devices/DEV/data"
        + "/Containers/Data/Application/F465616D-2D53-4E20-8EEC-3D3D32A0B82F"
    private static let newHome =
        "/Users/x/Library/Developer/CoreSimulator/Devices/DEV/data"
        + "/Containers/Data/Application/312E214E-F1EE-471A-A65A-A1921ACC3D77"

    private static let stale = oldHome + "/Documents/GoldbergVariatio4.m4a"
    private static let live = newHome + "/Documents/GoldbergVariatio4.m4a"

    @Test("a path from a previous container is re-anchored onto this one")
    func reanchorsAcrossContainers() {
        #expect(RecentPathAnchor.reanchored(Self.stale, home: Self.newHome) == Self.live)
    }

    /// It has to work for anything the app keeps, not just for Documents —
    /// Application Support is where the session fallback writes.
    @Test("the whole layout under the container is preserved")
    func preservesTheLayoutBelowTheUUID() {
        let deep = Self.oldHome + "/Library/Application Support/Artscribe/Sessions/a.artscripture"
        #expect(
            RecentPathAnchor.reanchored(deep, home: Self.newHome)
                == Self.newHome + "/Library/Application Support/Artscribe/Sessions/a.artscripture")
    }

    /// **A no-op on the Mac, by construction.** No macOS path contains the
    /// marker, so every one of these functions leaves a desktop path alone —
    /// which is why the rule can be a pure function rather than an `#if`.
    @Test("a macOS path is not container-shaped and is left alone")
    func macPathsAreUntouched() {
        let mac = "/Users/x/Music/Delfeayo's Dilemma.flac"
        #expect(RecentPathAnchor.reanchored(mac, home: "/Users/x") == nil)
        #expect(
            RecentPathAnchor.healed(
                URL(fileURLWithPath: mac), home: "/Users/x", exists: { _ in false }
            )
            .path == mac)
    }

    /// The container root on its own names no file, and must not resolve to the
    /// home directory.
    @Test("a bare container root re-anchors to nothing")
    func bareContainerRootIsNotAFile() {
        #expect(RecentPathAnchor.reanchored(Self.oldHome, home: Self.newHome) == nil)
        #expect(RecentPathAnchor.reanchored(Self.oldHome + "/", home: Self.newHome) == nil)
    }

    // MARK: - healed

    @Test("a dead container path heals to the live one")
    func healsWhatIsBroken() {
        let healed = RecentPathAnchor.healed(
            URL(fileURLWithPath: Self.stale), home: Self.newHome,
            exists: { $0 == Self.live })
        #expect(healed.path == Self.live)
    }

    @Test("a path that still opens is never rewritten")
    func leavesWorkingPathsAlone() {
        let healed = RecentPathAnchor.healed(
            URL(fileURLWithPath: Self.stale), home: Self.newHome,
            exists: { _ in true })
        #expect(healed.path == Self.stale, "a readable file was rewritten out from under itself")
    }

    /// **Never drops an entry.** `fileExists` says no for an iCloud Drive file
    /// that has not been downloaded, for an unmounted volume, and for anything
    /// reachable only through a security-scoped bookmark — all of which open
    /// perfectly a moment later. Dropping on that answer would empty Open Recent
    /// for every iPad user who keeps their music in Files.
    @Test("an entry that exists nowhere is kept as it was")
    func keepsUnresolvableEntries() {
        let elsewhere = "/private/var/mobile/Library/CloudStorage/iCloud~Drive/take.wav"
        let healed = RecentPathAnchor.healed(
            URL(fileURLWithPath: elsewhere), home: Self.newHome, exists: { _ in false })
        #expect(healed.path == elsewhere)
    }

    // MARK: - through the list

    @Test("the list heals the stale entry and keeps the rest in order")
    @MainActor
    func theListHealsInPlace() {
        let other = "/private/var/mobile/Library/CloudStorage/take.wav"
        let usable = RecentFiles.usable(
            [URL(fileURLWithPath: Self.stale), URL(fileURLWithPath: other)],
            home: Self.newHome,
            exists: { $0 == Self.live })
        #expect(usable.map(\.path) == [Self.live, other])
    }
}
